version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: server
    entrypoint: dockerize -wait tcp://database:3306 -timeout 20s node app.js
    depends_on: 
      - db
    ports:
      - "3333:3333"
    networks:
      - main-network

  webserver:
    image: nginx
    container_name: webserver
    ports:
      - "8080:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - nodejs
    networks:
      - main-network

  db:
    image: mysql:5.7 
    command: --innodb-use-native-aio=0
    container_name: database
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - main-network           

networks:
  main-network:
    driver: bridge